// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1956bc39-45fe-4eb7-985e-f008d203e80a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KKSbG9YRG",
    "aws_user_pools_web_client_id": "68h901m3omcq9r5i4d0v924d5o",
    "aws_appsync_graphqlEndpoint": "https://3df2slfjlraaldvnpgwl2isp6i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "profile-images-buckert-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
